/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securityhw1;
import java.util.Arrays;
/**
 *
 * @author hp
 */
public class NewJFrame extends javax.swing.JFrame {
String Question;
String input;
String encrypted_String;
int key;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Q1", "Q2", " " }));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("encrypt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Choose Question");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Input");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("key");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("encrypted data");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("decrypt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("decrypted data");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)))
                                .addGap(35, 35, 35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(106, 106, 106)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel4))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Question = (String)this.jComboBox1.getSelectedItem();
input = this.jTextArea1.getText();


if(Question.equals("Q1")){
    key= Integer.parseInt((String) this.jTextField2.getText());
    encryptQ1(input,key);
}
else{
    encryptQ2(input);    
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Question = (String)this.jComboBox1.getSelectedItem();
  String encrypt = (String)this.jTextArea3.getText();
if(Question.equals("Q1")){
    key= Integer.parseInt((String) this.jTextField2.getText());

    decryptQ1(encrypt,key);
}
else{
       decryptQ2(encrypt); 
} // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public String encryptQ1(String in,int key){
   String input = in.toUpperCase();
     int length = input.length();
      String Letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
     char[] encrypted_Data = new char[length];
     
for (int i = 0; i < length; i++) {
     int Position = Letters.indexOf(input.charAt(i));
            int Val = (key + Position) % 26;
           
           encrypted_Data[i]=Letters.charAt(Val);
}
 encrypted_String = new String(encrypted_Data);
this.jTextArea3.setText(encrypted_String);
return encrypted_String;
   
}

public void decryptQ1(String input,int key){
  
     int length = input.length();
      String Letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
      
     char[] decrypted_Data = new char[length];

        for (int i = 0; i < length; i++) {
            int Position = Letters.indexOf(input.charAt(i));
            int Val = (Position - key) % 26;
            if (Val < 0)
            {
               Val = Letters.length() + Val;
            }
             decrypted_Data[i]=Letters.charAt(Val);
        }
  String decrypted_String = new String(decrypted_Data);
this.jLabel6.setText(decrypted_String);
   
}

public void encryptQ2(String in){
   String in2 = in.replace("\n", "").replace("\r", "");
     String input = in2.toUpperCase();
     int length = input.length();
      String Letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
     char[] encrypted_Data = new char[length];
      String encrypt1 = "ZXCVBNMASDFGHJKLQWERTYUIOP";
     
for (int i = 0; i < length; i++) {
     int Position = Letters.indexOf(input.charAt(i));
            int Val = ( Position) % 26;
           
           encrypted_Data[i]=encrypt1.charAt(Val);
}
 encrypted_String = new String(encrypted_Data);
this.jTextArea3.setText(encrypted_String);

   
    
     
    

}

public void decryptQ2(String in){
     String input = in.toUpperCase();
 int length = input.length();
 char[] decrypted_Data = new char[length];
 for(int a = 0 ; a < length ; a++ ){
     decrypted_Data[a] = input.charAt(a);
 }
 char[] Character = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U',
 'V','W','X','Y','Z'};
 int count_a = 0;
int count_b = 0;
int count_c =0  , count_d =0,count_e=0 , count_f=0,count_g =0, count_h=0,
         count_i=0 , count_j=0,count_k=0 , count_l=0,count_m=0 , count_n=0,count_o=0 , count_p=0,
         count_q=0 , count_r=0,count_s=0 , count_t=0,count_u=0 , count_v=0,
         count_w=0 , count_x=0,count_y=0 , count_z = 0 ;

for(int i = 0 ; i < length ; i++){
     if(input.charAt(i) == 'A'){count_a = count_a+1;}
     else if(input.charAt(i) == 'B'){count_b = count_b+1;}
     else if(input.charAt(i) == 'C'){count_c = count_c+1;}
     else if(input.charAt(i) == 'D'){count_d = count_d+1;}
     else if(input.charAt(i) == 'E'){count_e = count_e+1;}
     else if(input.charAt(i) == 'F'){count_f = count_f+1;}
     else if(input.charAt(i) == 'G'){count_g = count_g+1;}
     else if(input.charAt(i) == 'H'){count_h = count_h+1;}
     else if(input.charAt(i) == 'I'){count_i = count_i+1;}
     else if(input.charAt(i) == 'j'){count_j = count_j+1;}
     else if(input.charAt(i) == 'K'){count_k = count_k+1;}
     else if(input.charAt(i) == 'L'){count_l = count_l+1;}
     else if(input.charAt(i) == 'M'){count_m = count_m+1;}
     else if(input.charAt(i) == 'N'){count_n = count_n+1;}
     else if(input.charAt(i) == 'O'){count_o = count_o+1;}
     else if(input.charAt(i) == 'P'){count_p = count_p+1;}
     else if(input.charAt(i) == 'Q'){count_q = count_q+1;}  
     else if(input.charAt(i) == 'R'){count_r = count_r+1;}
     else if(input.charAt(i) == 'S'){count_s = count_s+1;}
     else if(input.charAt(i) == 'T'){count_t = count_t+1;}
     else if(input.charAt(i) == 'U'){count_u = count_u+1;}
     else if(input.charAt(i) == 'V'){count_v = count_v+1;}
     else if(input.charAt(i) == 'W'){count_w = count_w+1;}
     else if(input.charAt(i) == 'X'){count_x = count_x+1;}
     else if(input.charAt(i) == 'Y'){count_y = count_y+1;}
     else if(input.charAt(i) == 'Z'){count_z = count_z+1;}
                                     
 }
 
 int array[] = new int[26];
 array[0] = count_a;array[1] = count_b;array[2] = count_c;array[3] = count_d;array[4] = count_e;
 array[5] = count_f;array[6] = count_g;array[7] = count_h;array[8] = count_i;array[9] = count_j;
 array[10] = count_k;array[11] = count_l;array[12] = count_m;array[13] = count_n;array[14] = count_o;
 array[15] = count_p;array[16] = count_q;array[17] = count_r;array[18] = count_s;array[19] = count_t;
 array[20] = count_u;array[21] = count_v;array[22] = count_w;array[23] = count_x;array[24] = count_y;
 array[25] = count_z;
 
 int k,m;
 int s = 26;
 int tmp ;
 char tmpe ;
 for(k = 0 ; k < s - 1 ; k++){
     for(m=0 ; m < s-k-1 ; m++){
         if(array[m]>array[m+1]){
             
         
           tmp = array[m] ;
           array[m] = array[m+1];
           array[m+1] = tmp;
           tmpe = Character[m];
           Character[m] = Character[m+1];
           Character[m+1] = tmpe;
     }}
 }
 System.out.print(Character);
 String result= "" ;
 for(int i = 0 ; i< length ; i++){
    if(input.charAt(i) == Character[25]){ result = result.concat("E");}
    else if(input.charAt(i) == Character[24]){ result = result.concat("T");}
    else if(input.charAt(i) == Character[23]){ result = result.concat("A");}
    else if(input.charAt(i) == Character[22]){ result = result.concat("O");}
    else if(input.charAt(i) == Character[21]){ result = result.concat("I");}
    else if(input.charAt(i) == Character[20]){ result = result.concat("N");}
    else if(input.charAt(i) == Character[19]){ result = result.concat("S");}
    else if(input.charAt(i) == Character[18]){ result = result.concat("R");}
    else if(input.charAt(i) == Character[17]){ result = result.concat("H");}
    else if(input.charAt(i) == Character[16]){ result = result.concat("D");}
    else if(input.charAt(i) == Character[15]){ result = result.concat("L");}
    else if(input.charAt(i) == Character[14]){ result = result.concat("U");}
    else if(input.charAt(i) == Character[13]){ result = result.concat("C");}
    else if(input.charAt(i) == Character[12]){ result = result.concat("M");}
    else if(input.charAt(i) == Character[11]){ result = result.concat("F");}
    else if(input.charAt(i) == Character[10]){ result = result.concat("Y");}
    else if(input.charAt(i) == Character[9]){ result = result.concat("W");}
    else if(input.charAt(i) == Character[8]){ result = result.concat("G");}
    else if(input.charAt(i) == Character[7]){ result = result.concat("P");}
    else if(input.charAt(i) == Character[6]){ result = result.concat("B");}
    else if(input.charAt(i) == Character[5]){ result = result.concat("V");}
    else if(input.charAt(i) == Character[4]){ result = result.concat("K");}
    else if(input.charAt(i) == Character[3]){ result = result.concat("X");}
    else if(input.charAt(i) == Character[2]){ result = result.concat("Q");}
    else if(input.charAt(i) == Character[1]){ result = result.concat("J");}
    else if(input.charAt(i) == Character[0]){ result = result.concat("Z");}
  
}
 this.jLabel6.setText(result);
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
